version: '3'
services:
  webserver:
    build:
      context: ./bin/webserver
    container_name: ${PROJECT_NAME}webserver
    image: ${PROJECT_NAME}webserver
    restart: always
    ports:
      - ${PORT}:80
    external_links:
      - mysql
    links:
      - redis
    networks:
      - container_default
    volumes:
      - ${DOCUMENT_ROOT-./www}:/usr/share/apache2/www
      - ${VHOSTS_DIR-./config/apache2/sites-enabled}:/etc/apache2/sites-enabled/
      - ${PHP_INI-./config/php/php.ini}:/etc/php/ENV_PHP_VERSION/apache2/conf.d/php.ini
      - ./config/php/${APP_ENV}.ini:/etc/php/ENV_PHP_VERSION/apache2/conf.d/${APP_ENV}.ini
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  redis:
    build: ./bin/redis
    container_name: ${PROJECT_NAME}redis
    image: ${PROJECT_NAME}redis
    restart: always
    volumes:
      - /data/redis:/data
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - container_default
networks:
  container_default:
    external: true
